name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: gcc test.c
    - name: run
      run: ./a.out

    - name: Archive artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: result_file
        path: result.txt
        retention-days: 1
