name: C/C++ CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: "Echo parameters"
      run: |
        echo "-> REPO:" $GITHUB_REPOSITORY_OWNER $GITHUB_REPOSITORY $GITHUB_REF
        echo "-> Link: " "https://github.com/"$GITHUB_REPOSITORY".git#"$GITHUB_REF
        git clone "https://github.com/"$GITHUB_REPOSITORY".git#"$GITHUB_REF abc
    - name: Compile
      run: gcc test.c
    - name: run
      run: ./a.out

    - name: Archive artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: result_file
        path: result.txt
        retention-days: 1
