name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: "Echo parameters"
      run: echo context.repo.owner context.repo.repo $GITHUB_REF
    - name: Compile
      run: gcc test.c
    - name: run
      run: ./a.out

    - name: Archive artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: result_file
        path: result.txt
        retention-days: 1
